apiVersion: v1
kind: Namespace
metadata:
  name: tool-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: tool-test
  labels:
    toolforge: tool
spec:
  selector:
    matchLabels:
      test: test
  template:
    metadata:
      labels:
        test: test
    spec:
      containers:
        - command:
            - sleep
            - "3600"
          image: docker-registry.tools.wmflabs.org/toolforge-bullseye-standalone:latest
          name: test
