{{- if .Values.podSecurityPolicy.existingClusterRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "delete-crashing-pods.fullname" . }}-psp
  labels:
  {{- include "delete-crashing-pods.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.podSecurityPolicy.existingClusterRole }}
subjects:
  - kind: ServiceAccount
    name: {{ include "delete-crashing-pods.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
